### ISSUE TITLE
`Script system error` errors for barony-tier rulers trying to hire a Court Chaplain

### ISSUE THREAD

**Issue by pharaox** [pharaox/ek2_fixes#16]
**CK3 Version:** 1.8.2

**EK2 Version:** 0.12.1

**Summary:** There are messages in `error.log` similar to this one:

```
[22:08:18][jomini_script_system.cpp:263]: Script system error!
  Error: assign_councillor_type effect [ Daynas Lowborn of b_assurbalhet (Internal ID 12274) doesn't has an open council position of councillor_court_chaplain ]
  Script location: file: common/decisions/ek_religious_decisions.txt line: 1157
```

These errors are caused by `recruit_priest_liturgical_language_decision` being available to rulers that can't hire a `councillor_court_chaplain` council position, e.g. barony-tier. To fix the issue the availability of the council position could be checked explicitly.

**Comment by ARSOD-Z** [comment]
just fixed that yesterday lol good catch
