### ISSUE TITLE
`Script system error` errors for missing `background_terrain_scope` in events

### ISSUE THREAD

**Issue by pharaox** [pharaox/ek2_fixes#17]
**CK3 Version:** 1.8.2

**EK2 Version:** 0.12.1

**Summary:** There are messages in `error.log` similar to this one:

```
[23:18:43][jomini_script_system.cpp:263]: Script system error!
  Error: Undefined event target 'background_terrain_scope'
  Script location: file: common/event_backgrounds/01_event_backgrounds.txt line: 880
```

These errors are caused by various events in `ek_yearly_events.txt` and `ek_pilgrimage_events.txt` using `terrain_scope` as their `event_background`, but not setting `background_terrain_scope`. It seems all events using `terrain_scope` should set `background_terrain_scope` to some location relevant to the event.

**Comment by ARSOD-Z** [comment]
those are going to be deprecated for 1.9 anyway but good catch
