### ISSUE TITLE
`Script system error` errors for inviting a character who is already in an activity to `pilgrimage_activity`

### ISSUE THREAD

**Issue by pharaox** [pharaox/ek2_fixes#18]
**CK3 Version:** 1.8.2

**EK2 Version:** 0.12.1

**Summary:** There are a lot of messages in `error.log` similar to this one:

```
[21:43:40][jomini_script_system.cpp:263]: Script system error!
  Error: invite_character_to_activity effect [ Character is already in an activity ]
  Script location: file: common/activities/00_activity_pilgrimage.txt line: 34 file: events/activities/pilgrimage_activity/pilgrimage_events.txt line: 57
[21:43:40][jomini_script_system.cpp:263]: Script system error!
  Error: accept_invitation_for_character effect [ Accepting invite to activity you're not invited to ]
  Script location: file: common/activities/00_activity_pilgrimage.txt line: 35 file: events/activities/pilgrimage_activity/pilgrimage_events.txt line: 57
[21:44:18][jomini_script_system.cpp:263]: Script system error!
  Error: invite_character_to_activity effect [ Character is already in an activity ]
  Script location: file: common/activities/00_activity_pilgrimage.txt line: 34 file: events/activities/pilgrimage_activity/pilgrimage_events.txt line: 37
[21:44:18][jomini_script_system.cpp:263]: Script system error!
  Error: accept_invitation_for_character effect [ Accepting invite to activity you're not invited to ]
  Script location: file: common/activities/00_activity_pilgrimage.txt line: 35 file: events/activities/pilgrimage_activity/pilgrimage_events.txt line: 37
```

These errors indicate that a character who is already in an activity is being invited to `pilgrimage_activity`, even though `go_on_pilgrimage_decision` is using `is_available_adult = yes`, which includes a check for whether the character is in an activity. They are caused by a missing `else` in the changes introduced by EK2 to `go_on_pilgrimage_decision`, which causes both `pilgrimage.0999` and `pilgrimage.0001` events to fire for some AI characters.

**Comment by Reinstigwa** [comment]
This issue has plagued us for *a long* time, thanks!

**Comment by pharaox** [comment]
It took me some time to see this missing `else` as well.

**Comment by ARSOD-Z** [comment]
introducing that else would also mean that ai won't be able to do kyne's trials

this file is gonna be completely reworked for 1.9 anyways

**Comment by pharaox** [comment]
@ARSOD-Z

> introducing that else would also mean that ai won't be able to do kyne's trials

I guess then the proper fix would be to reorder the checks so that to check for the kyne's trial conditions first, then for `is_ai = yes`, and then the final else. The important thing is not to allow both `pilgrimage.0999` and `pilgrimage.0001` to fire.
