### ISSUE TITLE
`Unknown trigger type` error for `is_in_morrowind_council` in `error.log`

### ISSUE THREAD

**Issue by pharaox** [pharaox/ek2_fixes#5]
**CK3 Version:** 1.8.2

**EK2 Version:** 0.12.1

**Summary:** There are messages in `error.log` similar to this one:

```
[21:24:18][pdx_persistent_reader.cpp:252]: Error: "Unknown trigger type: is_in_morrowind_council, near line: 136" in file: "common/character_interactions/00_war.txt" near line: 136
```

The trigger `is_in_morrowind_council` no longer exists and the entire section that uses it in `00_war.txt` seems obsolete.

**Comment by Reinstigwa** [comment]
This is WIP stuff that was cleaned out of the public release since it wasn't ready to be released, seems this one reference was leftover when cleaning out the files.
