### ISSUE TITLE
`Unknown trigger type` error for `artifact_feature_animal_lynx_trigger` in `error.log`

### ISSUE THREAD

**Issue by pharaox** [pharaox/ek2_fixes#6]
**CK3 Version:** 1.8.2

**EK2 Version:** 0.12.1

**Summary:** There are messages in `error.log` similar to this one:

```
[21:24:18][pdx_persistent_reader.cpp:252]: Error: "Unknown trigger type: artifact_feature_animal_lynx_trigger, near line: 3366" in file: "common/artifacts/features/00_features.txt" near line: 3367
```

The vanilla trigger `artifact_feature_animal_lynx_trigger` has been commented out, but the `animal_hide_type_lynx` visual is still referencing it. This visual and all references to it should be commented out as well, similarly to `animal_hide_type_tiger` and other vanilla visuals.

**Comment by ARSOD-Z** [comment]
no point in fixing that since this file is gonna be rewritten from scratch for 1.9 but in the compatch effort it's fixed
